#!/bin/bash

# docron--Runs the daily - monthly system cron jobs on a 
# machine that has been shutdown during the scheduled time.

rootcron="/etc/crontab" #  this varies by linux system

if [ $# -ne 1 ] ; then
  echo "Usage: $0 [daily|weekly|monthly]" >&2
  exit 1
fi

# Fail if not run as root via checking ID value == 0 (ie root)

if [ "$(id -u)" -ne 0 ] ; then
  echo "$0: Command must be run as root or sudo" >&2
  exit 1
fi

# We will give an error if we can't find the relavant entries

job="$(awk "NF > 6 && /$1/ { for (i=7;i<=NF;i++) print \$i }" $rootcron)"

echo $job

if [ -z "$job" ] ; then  # no job? That must be an error
  echo "$0: Error: no $1 job found in $rootcron" >&2
  exit 1
fi

SHELL=$(which sh)  # use crons default

eval $job
